## NUMPY

In [2]:
import numpy as np

In [6]:
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [10]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [12]:
arr2=np.array([[1,2,3,4,5],[3,4,5,6,7]])  #2d array
print(arr2)
arr2.shape

[[1 2 3 4 5]
 [3 4 5 6 7]]


(2, 5)

In [16]:
np.arange(0,10,3).reshape(4,1)

array([[0],
       [3],
       [6],
       [9]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
#Attributes of numpy
arr=np.array([[1,2,3,4,5]])
print(f"array :{arr}")
print(f"shape :{arr.shape}")
print(f"size :{arr.size}")
print(f"number of dimensions :{arr.ndim}")
print(f"Datatype :{arr.dtype}")
print(f"Item size in (bytes) :{arr.itemsize}")

array :[[1 2 3 4 5]]
shape :(1, 5)
size :5
number of dimensions :2
Datatype :int64
Item size in (bytes) :8


In [36]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,6,7,8])

#Element wise operations
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(np.round((arr1/arr2),2))

[ 5  7  9 11 13]
[-3 -3 -3 -3 -3]
[ 4 10 18 28 40]
[0.25 0.4  0.5  0.57 0.62]


In [39]:
arr=np.array([3,9,8,7,6])

print(np.round(np.sqrt(arr),2))
print(np.round(np.exp(arr),2))
print(np.round(np.cos(arr),2))
print(np.round(np.sin(arr),2))
print(np.round(np.log(arr),2))

[1.73 3.   2.83 2.65 2.45]
[  20.09 8103.08 2980.96 1096.63  403.43]
[-0.99 -0.91 -0.15  0.75  0.96]
[ 0.14  0.41  0.99  0.66 -0.28]
[1.1  2.2  2.08 1.95 1.79]


In [75]:
# array slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

print(f"accessing 1:     {arr[0][0]}")
print(f"accessing 5,6,9,10:    {arr[1:,:2]}")
print(f"accessing 3,4,7,8:     {arr[0:2,2:4]}")
print(f"accessing 6,7,10,11:     {arr[1:,1:3]}")


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
accessing 1:     1
accessing 5,6,9,10:    [[ 5  6]
 [ 9 10]]
accessing 3,4,7,8:     [[3 4]
 [7 8]]
accessing 6,7,10,11:     [[ 6  7]
 [10 11]]


In [76]:
### MODIFY ARRAY ELEMENTS

arr[0][0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [77]:
arr[1:]=90
print(arr)

[[100   2   3   4]
 [ 90  90  90  90]
 [ 90  90  90  90]]


In [86]:
data=np.array([1,2,3,4,5,6])

print(np.mean(data))
print(np.round(np.std(data),2))

normalized_data = (data -np.mean(data)) / np.std(data)
print("Normalized data:", np.round(normalized_data,2))

3.5
1.71
Normalized data: [-1.46 -0.88 -0.29  0.29  0.88  1.46]


In [87]:
data=np.array([2,3,4,6,6,7])
print(np.mean(data))
print(np.std(data))
print(np.var(data))
print(np.median(data))

4.666666666666667
1.7950549357115013
3.222222222222222
5.0


In [92]:
data=np.array([2,3,4,5,6,4])
data[(data>1) & (data<=4)]

array([2, 3, 4, 4])

In [5]:
# joining arrays
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

print(np.concatenate([arr1,arr2]))

[ 1  2  3  4  5  6  7  8  9 10]


In [95]:
# splitting array
np.array_split(arr1,3)

[array([1, 2]), array([3, 4]), array([5])]

In [98]:
# search

print(np.where(arr1==4))

(array([3]),)


In [6]:
np.sort(arr1)

array([1, 2, 3, 4, 5])

### PANDAS

In [7]:
import pandas as pd

In [9]:
#series
data=[1,2,3,4,5]
series=pd.Series(data)    # Series automatically adds index, values and dtype

print(f"series :{series}")
print(type(series))

series :0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>


In [14]:
dta1={
    'name' : 'huzaifa',
    'reg'  : '1262',
    'date of birth' : '24-8-2003'
}
dta1_series=pd.Series(dta1)
print(dta1_series)

name               huzaifa
reg                   1262
date of birth    24-8-2003
dtype: str


In [15]:
data=[1,2,3,4]
index=['a','b','c','d']
pd.Series(data,index=index)

a    1
b    2
c    3
d    4
dtype: int64

In [18]:
#Data frame
football_players={
    'Name':['lional messi','cristiano ronaldo','neymar jr'],   # DataFrame is a 2D table (rows and columns)
    'age' :[38,41,35],                                         # just like an Excel sheet in Python
    'country': ['Argentina','portugal','Brazil']
}
data=pd.DataFrame(football_players)
print(data)

print(type(data))

                Name  age    country
0       lional messi   38  Argentina
1  cristiano ronaldo   41   portugal
2          neymar jr   35     Brazil
<class 'pandas.DataFrame'>


In [20]:
# creating a DataFrame from a list of Dictionaries

data=[
    {"Name":"Huzaifa","age":23,"country":"Pakistan"},
    {"Name":"Alex","age":21,"country":"England"},
    {"Name":"Rodriquez","age":20,"country":"Brazil"},
    {"Name":"Sanchez","age":19,"country":"colombia"},
]
dta2=pd.DataFrame(data)
print(dta2)
print(type(dta2))

        Name  age   country
0    Huzaifa   23  Pakistan
1       Alex   21   England
2  Rodriquez   20    Brazil
3    Sanchez   19  colombia
<class 'pandas.DataFrame'>


In [22]:
df=pd.read_csv("data.csv")
print(df)

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-0

In [26]:
df.head(5)

,Date,Category,Value,Product,Sales,Region
0,2023-01-01,A,28.0,Product1,754.0,East
1,2023-01-02,B,39.0,Product3,110.0,North
2,2023-01-03,C,32.0,Product2,398.0,East
3,2023-01-04,B,8.0,Product1,522.0,East
4,2023-01-05,B,26.0,Product3,869.0,North


In [27]:
df.tail(5)

,Date,Category,Value,Product,Sales,Region
45,2023-02-15,B,99.0,Product2,599.0,West
46,2023-02-16,B,6.0,Product1,938.0,South
47,2023-02-17,B,69.0,Product3,143.0,West
48,2023-02-18,C,65.0,Product3,182.0,North
49,2023-02-19,C,11.0,Product3,708.0,North


In [39]:
df['Region']

0      East
1     North
2      East
3      East
4     North
5      West
6      East
7      West
8      West
9      West
10    North
11     West
12    South
13     East
14     West
15    North
16    South
17     West
18     West
19     East
20    South
21    South
22    North
23     West
24     East
25     West
26    North
27    North
28    North
29    South
30     West
31     West
32    South
33     East
34     West
35     West
36     East
37    North
38    South
39     West
40     East
41     East
42     West
43     East
44     East
45     West
46    South
47     West
48    North
49    North
Name: Region, dtype: str

In [37]:
dta2

,Name,age,country
0,Huzaifa,23,Pakistan
1,Alex,21,England
2,Rodriquez,20,Brazil
3,Sanchez,19,colombia


In [38]:
dta2['Name']

0      Huzaifa
1         Alex
2    Rodriquez
3      Sanchez
Name: Name, dtype: str

In [52]:
df.loc[0]  # access row where index = 0   same as serial number

Date        2023-01-01
Category             A
Value             28.0
Product       Product1
Sales            754.0
Region            East
Name: 0, dtype: object

In [53]:
df.iloc[49] # access data where index = 49

Date        2023-02-19
Category             C
Value             11.0
Product       Product3
Sales            708.0
Region           North
Name: 49, dtype: object

In [61]:
df.loc[1]["Date"]

'2023-01-02'

In [63]:
df.iloc[1]['Category']

'B'

In [65]:
df['Sales']

0     754.0
1     110.0
2     398.0
3     522.0
4     869.0
5     192.0
6     936.0
7     488.0
8     772.0
9     834.0
10    842.0
11      NaN
12    628.0
13    423.0
14    893.0
15    895.0
16    511.0
17    108.0
18    578.0
19    736.0
20    606.0
21    992.0
22    942.0
23    342.0
24    458.0
25    584.0
26    619.0
27    224.0
28    617.0
29    737.0
30    735.0
31    189.0
32    338.0
33      NaN
34    669.0
35      NaN
36    177.0
37      NaN
38    408.0
39    155.0
40    578.0
41    256.0
42    164.0
43    949.0
44    830.0
45    599.0
46    938.0
47    143.0
48    182.0
49    708.0
Name: Sales, dtype: float64

In [66]:
df

,Date,Category,Value,Product,Sales,Region
0,2023-01-01,A,28.0,Product1,754.0,East
1,2023-01-02,B,39.0,Product3,110.0,North
2,2023-01-03,C,32.0,Product2,398.0,East
3,2023-01-04,B,8.0,Product1,522.0,East
4,2023-01-05,B,26.0,Product3,869.0,North
5,2023-01-06,B,54.0,Product3,192.0,West
6,2023-01-07,A,16.0,Product1,936.0,East
7,2023-01-08,C,89.0,Product1,488.0,West
8,2023-01-09,C,37.0,Product3,772.0,West
9,2023-01-10,A,22.0,Product2,834.0,West


In [67]:
df.at[1,'Region']

'North'

In [69]:
df.iat[1,0]

'2023-01-02'

In [79]:
df['Salary']=[1200,2000,2000,2999,2888,2888,999,8888,2000,234,555,544,3,33,3,3,32,43,4,4,4,5,5,3,44,4,5,3,3,32,2,32,3,2,34,434,5,45,5,6,767,7,67,6,7,45,3,3,2,323]
df

,Date,Category,Value,Product,Sales,Region,Salary
0,2023-01-01,A,28.0,Product1,754.0,East,1200
1,2023-01-02,B,39.0,Product3,110.0,North,2000
2,2023-01-03,C,32.0,Product2,398.0,East,2000
3,2023-01-04,B,8.0,Product1,522.0,East,2999
4,2023-01-05,B,26.0,Product3,869.0,North,2888
5,2023-01-06,B,54.0,Product3,192.0,West,2888
6,2023-01-07,A,16.0,Product1,936.0,East,999
7,2023-01-08,C,89.0,Product1,488.0,West,8888
8,2023-01-09,C,37.0,Product3,772.0,West,2000
9,2023-01-10,A,22.0,Product2,834.0,West,234


In [80]:
#remove a column
df.drop('Salary',axis=1,inplace =True) # Drop a column from the DataFrame
                                       # axis=1    → tells pandas we are dropping a COLUMN (not a row)
                                       # inplace=True → modify the original df directly (no new df created)

In [81]:
df

,Date,Category,Value,Product,Sales,Region
0,2023-01-01,A,28.0,Product1,754.0,East
1,2023-01-02,B,39.0,Product3,110.0,North
2,2023-01-03,C,32.0,Product2,398.0,East
3,2023-01-04,B,8.0,Product1,522.0,East
4,2023-01-05,B,26.0,Product3,869.0,North
5,2023-01-06,B,54.0,Product3,192.0,West
6,2023-01-07,A,16.0,Product1,936.0,East
7,2023-01-08,C,89.0,Product1,488.0,West
8,2023-01-09,C,37.0,Product3,772.0,West
9,2023-01-10,A,22.0,Product2,834.0,West


In [89]:
#add Value to a column
df['Value']=df['Value']+1
df

,Date,Category,Value,Product,Sales,Region
0,2023-01-01,A,29.0,Product1,754.0,East
1,2023-01-02,B,40.0,Product3,110.0,North
2,2023-01-03,C,33.0,Product2,398.0,East
3,2023-01-04,B,9.0,Product1,522.0,East
4,2023-01-05,B,27.0,Product3,869.0,North
5,2023-01-06,B,55.0,Product3,192.0,West
6,2023-01-07,A,17.0,Product1,936.0,East
7,2023-01-08,C,90.0,Product1,488.0,West
8,2023-01-09,C,38.0,Product3,772.0,West
9,2023-01-10,A,23.0,Product2,834.0,West


In [92]:
df.drop(0,inplace=True)

In [93]:
df

,Date,Category,Value,Product,Sales,Region
1,2023-01-02,B,40.0,Product3,110.0,North
2,2023-01-03,C,33.0,Product2,398.0,East
3,2023-01-04,B,9.0,Product1,522.0,East
4,2023-01-05,B,27.0,Product3,869.0,North
5,2023-01-06,B,55.0,Product3,192.0,West
6,2023-01-07,A,17.0,Product1,936.0,East
7,2023-01-08,C,90.0,Product1,488.0,West
8,2023-01-09,C,38.0,Product3,772.0,West
9,2023-01-10,A,23.0,Product2,834.0,West
10,2023-01-11,B,8.0,Product1,842.0,North


In [95]:
# Display the data types of each column
print(f"Datatypes : {df.dtypes}")
# Describe the DataFrame
print(f"statistical summary : {df.describe()}")

Datatypes : Date            str
Category        str
Value       float64
Product         str
Sales       float64
Region          str
dtype: object
statistical summary :             Value       Sales
count   46.000000   45.000000
mean    53.260870  552.755556
std     29.152804  276.075513
min      3.000000  108.000000
25%     29.000000  338.000000
50%     56.000000  584.000000
75%     71.000000  772.000000
max    100.000000  992.000000
