## NUMPY

In [1]:
import numpy as np

In [6]:
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [10]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [12]:
arr2=np.array([[1,2,3,4,5],[3,4,5,6,7]])  #2d array
print(arr2)
arr2.shape

[[1 2 3 4 5]
 [3 4 5 6 7]]


(2, 5)

In [16]:
np.arange(0,10,3).reshape(4,1)

array([[0],
       [3],
       [6],
       [9]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
#Attributes of numpy
arr=np.array([[1,2,3,4,5]])
print(f"array :{arr}")
print(f"shape :{arr.shape}")
print(f"size :{arr.size}")
print(f"number of dimensions :{arr.ndim}")
print(f"Datatype :{arr.dtype}")
print(f"Item size in (bytes) :{arr.itemsize}")

array :[[1 2 3 4 5]]
shape :(1, 5)
size :5
number of dimensions :2
Datatype :int64
Item size in (bytes) :8


In [36]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,6,7,8])

#Element wise operations
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(np.round((arr1/arr2),2))

[ 5  7  9 11 13]
[-3 -3 -3 -3 -3]
[ 4 10 18 28 40]
[0.25 0.4  0.5  0.57 0.62]


In [39]:
arr=np.array([3,9,8,7,6])

print(np.round(np.sqrt(arr),2))
print(np.round(np.exp(arr),2))
print(np.round(np.cos(arr),2))
print(np.round(np.sin(arr),2))
print(np.round(np.log(arr),2))

[1.73 3.   2.83 2.65 2.45]
[  20.09 8103.08 2980.96 1096.63  403.43]
[-0.99 -0.91 -0.15  0.75  0.96]
[ 0.14  0.41  0.99  0.66 -0.28]
[1.1  2.2  2.08 1.95 1.79]


In [75]:
# array slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

print(f"accessing 1:     {arr[0][0]}")
print(f"accessing 5,6,9,10:    {arr[1:,:2]}")
print(f"accessing 3,4,7,8:     {arr[0:2,2:4]}")
print(f"accessing 6,7,10,11:     {arr[1:,1:3]}")


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
accessing 1:     1
accessing 5,6,9,10:    [[ 5  6]
 [ 9 10]]
accessing 3,4,7,8:     [[3 4]
 [7 8]]
accessing 6,7,10,11:     [[ 6  7]
 [10 11]]


In [76]:
### MODIFY ARRAY ELEMENTS

arr[0][0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [77]:
arr[1:]=90
print(arr)

[[100   2   3   4]
 [ 90  90  90  90]
 [ 90  90  90  90]]


In [86]:
data=np.array([1,2,3,4,5,6])

print(np.mean(data))
print(np.round(np.std(data),2))

normalized_data = (data -np.mean(data)) / np.std(data)
print("Normalized data:", np.round(normalized_data,2))

3.5
1.71
Normalized data: [-1.46 -0.88 -0.29  0.29  0.88  1.46]


In [87]:
data=np.array([2,3,4,6,6,7])
print(np.mean(data))
print(np.std(data))
print(np.var(data))
print(np.median(data))

4.666666666666667
1.7950549357115013
3.222222222222222
5.0


In [92]:
data=np.array([2,3,4,5,6,4])
data[(data>1) & (data<=4)]

array([2, 3, 4, 4])

In [94]:
# joining arrays
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

print(np.concatenate([arr1,arr2]))

[ 1  2  3  4  5  6  7  8  9 10]


In [95]:
# splitting array
np.array_split(arr1,3)

[array([1, 2]), array([3, 4]), array([5])]

In [98]:
# search

print(np.where(arr1==4))

(array([3]),)


In [102]:
np.sort(arr1,0)


array([1, 2, 3, 4, 5])